CREATE TABLE users
(user_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(75) NOT NULL UNIQUE,
email VARCHAR(200) NOT NULL UNIQUE,
password VARCHAR(150) NOT NULL,
is_admin BIT NOT NULL DEFAULT 0,
is_verified BIT NOT NULL DEFAULT 0);